-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.achievements
(
    achievement_id bigserial NOT NULL,
    achievement_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    achievement_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    points_value integer NOT NULL DEFAULT 0,
    badge_icon character varying(200) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT achievements_pkey PRIMARY KEY (achievement_id),
    CONSTRAINT achievements_achievement_code_key UNIQUE (achievement_code)
);

CREATE TABLE IF NOT EXISTS public.admin_logs
(
    log_id bigserial NOT NULL,
    admin_id bigint NOT NULL,
    action_type character varying(100) COLLATE pg_catalog."default" NOT NULL,
    target_type character varying(50) COLLATE pg_catalog."default",
    target_id bigint,
    description text COLLATE pg_catalog."default",
    ip_address inet,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT admin_logs_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS public.ban_history
(
    ban_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    admin_id bigint NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    ban_start timestamp with time zone NOT NULL DEFAULT now(),
    ban_end timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ban_history_pkey PRIMARY KEY (ban_id)
);

CREATE TABLE IF NOT EXISTS public.broadcast_messages
(
    message_id bigserial NOT NULL,
    admin_id bigint NOT NULL,
    title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    message_type character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'info'::character varying,
    priority character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'medium'::character varying,
    is_active boolean NOT NULL DEFAULT true,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT broadcast_messages_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS public.daily_stats
(
    stat_date date NOT NULL,
    total_games_active integer NOT NULL DEFAULT 0,
    total_games_played integer NOT NULL DEFAULT 0,
    sessions_created integer NOT NULL DEFAULT 0,
    peak_concurrent_users integer NOT NULL DEFAULT 0,
    new_registrations integer NOT NULL DEFAULT 0,
    CONSTRAINT daily_stats_pkey PRIMARY KEY (stat_date)
);

CREATE TABLE IF NOT EXISTS public.feedback
(
    feedback_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    category feedback_category NOT NULL,
    subject character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    status feedback_status NOT NULL DEFAULT 'pending'::feedback_status,
    priority character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'medium'::character varying,
    admin_response text COLLATE pg_catalog."default",
    admin_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone,
    CONSTRAINT feedback_pkey PRIMARY KEY (feedback_id)
);

CREATE TABLE IF NOT EXISTS public.friendships
(
    user_id bigint NOT NULL,
    friend_id bigint NOT NULL,
    status friendship_status NOT NULL DEFAULT 'requested'::friendship_status,
    requested_at timestamp with time zone NOT NULL DEFAULT now(),
    accepted_at timestamp with time zone,
    CONSTRAINT friendships_pkey PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS public.game_messages
(
    message_id bigserial NOT NULL,
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    message_text text COLLATE pg_catalog."default" NOT NULL,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT game_messages_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS public.game_rooms
(
    room_id bigserial NOT NULL,
    room_code character varying(12) COLLATE pg_catalog."default" NOT NULL,
    room_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(200) COLLATE pg_catalog."default",
    host_user_id bigint NOT NULL,
    max_player integer NOT NULL DEFAULT 2,
    min_player integer NOT NULL DEFAULT 2,
    is_private boolean NOT NULL DEFAULT false,
    game_mode game_mode NOT NULL DEFAULT 'versus'::game_mode,
    room_status room_status NOT NULL DEFAULT 'open'::room_status,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    start_time timestamp with time zone,
    finished_time timestamp with time zone,
    CONSTRAINT game_rooms_pkey PRIMARY KEY (room_id),
    CONSTRAINT game_rooms_room_code_key UNIQUE (room_code)
);

CREATE TABLE IF NOT EXISTS public.game_stats
(
    game_stat_id bigserial NOT NULL,
    match_id bigint NOT NULL,
    game_number smallint NOT NULL,
    player_id bigint NOT NULL,
    is_winner boolean NOT NULL DEFAULT false,
    pieces integer NOT NULL DEFAULT 0,
    attack_lines integer NOT NULL DEFAULT 0,
    time_seconds numeric(7, 2) NOT NULL,
    pps numeric(5, 2) NOT NULL DEFAULT 0.00,
    apm numeric(6, 2) NOT NULL DEFAULT 0.00,
    lines_cleared integer DEFAULT 0,
    pieces_placed integer DEFAULT 0,
    attacks_sent integer DEFAULT 0,
    garbage_received integer DEFAULT 0,
    holds integer DEFAULT 0,
    inputs integer DEFAULT 0,
    elapsed_ms integer DEFAULT 0,
    CONSTRAINT game_stats_pkey PRIMARY KEY (game_stat_id),
    CONSTRAINT game_stats_match_game_player_key UNIQUE (match_id, game_number, player_id)
);

COMMENT ON TABLE public.game_stats
    IS 'Lưu chi tiết chỉ số của từng người chơi trong từng ván đấu (game). Mỗi ván có 2 hàng (1 cho mỗi player).';

COMMENT ON COLUMN public.game_stats.game_number
    IS 'Số thứ tự ván (1, 2, hoặc 3)';

COMMENT ON COLUMN public.game_stats.is_winner
    IS 'TRUE nếu player này thắng ván này';

COMMENT ON COLUMN public.game_stats.pieces
    IS '[DEPRECATED] Sử dụng pieces_placed thay thế';

COMMENT ON COLUMN public.game_stats.attack_lines
    IS '[DEPRECATED] Sử dụng attacks_sent thay thế';

COMMENT ON COLUMN public.game_stats.time_seconds
    IS '[DEPRECATED] Sử dụng elapsed_ms thay thế';

COMMENT ON COLUMN public.game_stats.pps
    IS 'Pieces Per Second - Tốc độ đặt Tetromino';

COMMENT ON COLUMN public.game_stats.apm
    IS 'Attack Per Minute - Số dòng rác gửi đi mỗi phút';

COMMENT ON COLUMN public.game_stats.lines_cleared
    IS 'Số dòng đã xóa trong ván này';

COMMENT ON COLUMN public.game_stats.pieces_placed
    IS 'Số Tetromino đã đặt';

COMMENT ON COLUMN public.game_stats.attacks_sent
    IS 'Số dòng rác đã gửi';

COMMENT ON COLUMN public.game_stats.garbage_received
    IS 'Số dòng rác đã nhận';

COMMENT ON COLUMN public.game_stats.holds
    IS 'Số lần sử dụng hold';

COMMENT ON COLUMN public.game_stats.inputs
    IS 'Tổng số input (phím bấm)';

COMMENT ON COLUMN public.game_stats.elapsed_ms
    IS 'Thời gian chơi (milliseconds)';

CREATE TABLE IF NOT EXISTS public.leaderboards
(
    user_id bigint NOT NULL,
    season_id bigint NOT NULL,
    rank_position integer NOT NULL,
    rank_points integer NOT NULL DEFAULT 0,
    games_played integer NOT NULL DEFAULT 0,
    winrate numeric(5, 2) NOT NULL DEFAULT 0.00,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT leaderboards_pkey PRIMARY KEY (user_id, season_id)
);

CREATE TABLE IF NOT EXISTS public.matches
(
    match_id bigserial NOT NULL,
    match_guid uuid NOT NULL DEFAULT gen_random_uuid(),
    player1_id bigint NOT NULL,
    player2_id bigint NOT NULL,
    player1_wins integer NOT NULL DEFAULT 0,
    player2_wins integer NOT NULL DEFAULT 0,
    winner_id bigint,
    mode character varying(20) COLLATE pg_catalog."default" NOT NULL,
    match_timestamp timestamp with time zone NOT NULL DEFAULT now(),
    end_reason character varying(50) COLLATE pg_catalog."default" DEFAULT 'normal'::character varying,
    CONSTRAINT matches_pkey PRIMARY KEY (match_id),
    CONSTRAINT matches_match_guid_key UNIQUE (match_guid)
);

COMMENT ON TABLE public.matches
    IS 'Lưu thông tin tổng quan trận đấu BO3 (Best of 3). Mỗi trận có tối đa 3 ván.';

COMMENT ON COLUMN public.matches.match_guid
    IS 'UUID duy nhất để tracking trận đấu';

COMMENT ON COLUMN public.matches.player1_wins
    IS 'Số ván player 1 thắng trong trận BO3';

COMMENT ON COLUMN public.matches.player2_wins
    IS 'Số ván player 2 thắng trong trận BO3';

COMMENT ON COLUMN public.matches.winner_id
    IS 'ID người thắng trận BO3 (NULL nếu hòa)';

COMMENT ON COLUMN public.matches.mode
    IS 'Match mode: casual or ranked';

COMMENT ON COLUMN public.matches.end_reason
    IS 'Lý do kết thúc: normal, player1_disconnect, player2_disconnect, player1_afk, player2_afk';

CREATE TABLE IF NOT EXISTS public.messages
(
    message_id serial NOT NULL,
    recipient_id integer NOT NULL,
    sender_id integer,
    message_type character varying(30) COLLATE pg_catalog."default" NOT NULL DEFAULT 'system'::character varying,
    subject character varying(200) COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean DEFAULT false,
    is_starred boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT now(),
    read_at timestamp without time zone,
    deleted_at timestamp without time zone,
    CONSTRAINT messages_pkey PRIMARY KEY (message_id)
);

COMMENT ON TABLE public.messages
    IS 'Hộp thư của người chơi - lưu tất cả tin nhắn, thông báo';

COMMENT ON COLUMN public.messages.sender_id
    IS 'NULL = tin nhắn hệ thống, số = user_id của người gửi';

COMMENT ON COLUMN public.messages.metadata
    IS 'JSON data cho liên kết với feedback, report, broadcast, etc.';

CREATE TABLE IF NOT EXISTS public.room_settings
(
    room_id bigint NOT NULL,
    time_limit_seconds integer,
    line_clear_goal integer,
    line_limit_enable boolean NOT NULL DEFAULT false,
    hold_enable boolean NOT NULL DEFAULT true,
    ghost_piece_enable boolean NOT NULL DEFAULT true,
    hard_drop_enable boolean NOT NULL DEFAULT true,
    CONSTRAINT room_settings_pkey PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS public.seasons
(
    season_id bigserial NOT NULL,
    season_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date,
    is_active boolean NOT NULL DEFAULT false,
    CONSTRAINT seasons_pkey PRIMARY KEY (season_id)
);

CREATE TABLE IF NOT EXISTS public.sessions_players
(
    session_id bigint NOT NULL,
    user_id bigint NOT NULL,
    max_combo integer NOT NULL DEFAULT 0,
    max_b2b integer NOT NULL DEFAULT 0,
    apm integer NOT NULL DEFAULT 0,
    final_score integer NOT NULL DEFAULT 0,
    playing_seconds integer NOT NULL DEFAULT 0,
    is_winner boolean NOT NULL DEFAULT false,
    elo_change integer NOT NULL DEFAULT 0,
    attacks_sent integer NOT NULL DEFAULT 0,
    attacks_received integer NOT NULL DEFAULT 0,
    CONSTRAINT sessions_players_pkey PRIMARY KEY (session_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.tournaments
(
    tournament_id bigserial NOT NULL,
    tournament_code character varying(30) COLLATE pg_catalog."default",
    tournament_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    max_participants integer NOT NULL DEFAULT 64,
    prize_pool integer NOT NULL DEFAULT 0,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    status tournament_status NOT NULL DEFAULT 'scheduled'::tournament_status,
    created_by bigint,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT tournaments_pkey PRIMARY KEY (tournament_id),
    CONSTRAINT tournaments_tournament_code_key UNIQUE (tournament_code)
);

CREATE TABLE IF NOT EXISTS public.tournaments_participants
(
    tournament_id bigint NOT NULL,
    user_id bigint NOT NULL,
    registered_at timestamp with time zone NOT NULL DEFAULT now(),
    group_round integer,
    current_round integer,
    final_placement integer,
    CONSTRAINT tournaments_participants_pkey PRIMARY KEY (tournament_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.user_achievements
(
    user_id bigint NOT NULL,
    achievement_id bigint NOT NULL,
    earned_at timestamp with time zone NOT NULL DEFAULT now(),
    progress_value bigint NOT NULL DEFAULT 0,
    is_completed boolean NOT NULL DEFAULT false,
    CONSTRAINT user_achievements_pkey PRIMARY KEY (user_id, achievement_id)
);

CREATE TABLE IF NOT EXISTS public.user_reports
(
    report_id bigserial NOT NULL,
    reporter_id bigint NOT NULL,
    reported_user_id bigint,
    session_id bigint,
    report_type report_type NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    evidence_url character varying(500) COLLATE pg_catalog."default",
    status report_status NOT NULL DEFAULT 'pending'::report_status,
    admin_id bigint,
    admin_notes text COLLATE pg_catalog."default",
    action_taken character varying(500) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone,
    CONSTRAINT user_reports_pkey PRIMARY KEY (report_id)
);

CREATE TABLE IF NOT EXISTS public.user_stats
(
    user_id bigint NOT NULL,
    total_games_played integer NOT NULL DEFAULT 0,
    total_games_won integer NOT NULL DEFAULT 0,
    lines_cleared integer NOT NULL DEFAULT 0,
    highest_score integer NOT NULL DEFAULT 0,
    highest_level integer NOT NULL DEFAULT 0,
    highest_combo integer NOT NULL DEFAULT 0,
    total_playtime_sec integer NOT NULL DEFAULT 0,
    rating_points integer NOT NULL DEFAULT 0,
    elo_rating integer NOT NULL DEFAULT 1000,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_stats_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigserial NOT NULL,
    user_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email character varying(200) COLLATE pg_catalog."default" NOT NULL,
    password character varying(200) COLLATE pg_catalog."default" NOT NULL,
    country_code character(2) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    last_login timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    is_banned boolean NOT NULL DEFAULT false,
    is_verified boolean NOT NULL DEFAULT false,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'player'::character varying,
    elo_rating integer DEFAULT 1000,
    win_streak integer DEFAULT 0,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_user_name_key UNIQUE (user_name)
);

COMMENT ON COLUMN public.users.elo_rating
    IS 'ELO rating for ranked matches, starts at 1000';

COMMENT ON COLUMN public.users.win_streak
    IS 'Current win streak for bonus ELO calculation';

CREATE TABLE IF NOT EXISTS public.users_settings
(
    user_id bigint NOT NULL,
    das_delay_ms integer NOT NULL DEFAULT 150,
    arr_ms integer NOT NULL DEFAULT 30,
    soft_drop_rate integer NOT NULL DEFAULT 60,
    show_next_pieces integer NOT NULL DEFAULT 5,
    sound_enabled boolean NOT NULL DEFAULT true,
    music_enabled boolean NOT NULL DEFAULT true,
    sound_volume numeric(3, 2) NOT NULL DEFAULT 1.00,
    music_volume numeric(3, 2) NOT NULL DEFAULT 0.60,
    key_bindings jsonb NOT NULL DEFAULT '{}'::jsonb,
    theme_preference character varying(50) COLLATE pg_catalog."default" DEFAULT 'default'::character varying,
    language_pref character varying(10) COLLATE pg_catalog."default" DEFAULT 'en'::character varying,
    CONSTRAINT users_settings_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.admin_logs
    ADD CONSTRAINT admin_logs_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ban_history
    ADD CONSTRAINT ban_history_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.ban_history
    ADD CONSTRAINT ban_history_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.broadcast_messages
    ADD CONSTRAINT broadcast_messages_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_broadcast_admin
    ON public.broadcast_messages(admin_id);


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.feedback
    ADD CONSTRAINT feedback_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_feedback_user
    ON public.feedback(user_id);


ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT friendships_friend_id_fkey FOREIGN KEY (friend_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.friendships
    ADD CONSTRAINT friendships_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.game_messages
    ADD CONSTRAINT game_messages_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.game_rooms
    ADD CONSTRAINT game_rooms_host_user_id_fkey FOREIGN KEY (host_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.game_stats
    ADD CONSTRAINT game_stats_match_id_fkey FOREIGN KEY (match_id)
    REFERENCES public.matches (match_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_game_stats_match_id
    ON public.game_stats(match_id);


ALTER TABLE IF EXISTS public.game_stats
    ADD CONSTRAINT game_stats_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_game_stats_player_id
    ON public.game_stats(player_id);


ALTER TABLE IF EXISTS public.leaderboards
    ADD CONSTRAINT leaderboards_season_id_fkey FOREIGN KEY (season_id)
    REFERENCES public.seasons (season_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.leaderboards
    ADD CONSTRAINT leaderboards_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.matches
    ADD CONSTRAINT matches_player1_id_fkey FOREIGN KEY (player1_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.matches
    ADD CONSTRAINT matches_player2_id_fkey FOREIGN KEY (player2_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.matches
    ADD CONSTRAINT matches_winner_id_fkey FOREIGN KEY (winner_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_matches_winner
    ON public.matches(winner_id);


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fk_recipient FOREIGN KEY (recipient_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_messages_recipient
    ON public.messages(recipient_id);


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT fk_sender FOREIGN KEY (sender_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_messages_sender
    ON public.messages(sender_id);


ALTER TABLE IF EXISTS public.room_settings
    ADD CONSTRAINT room_settings_room_id_fkey FOREIGN KEY (room_id)
    REFERENCES public.game_rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS room_settings_pkey
    ON public.room_settings(room_id);


ALTER TABLE IF EXISTS public.sessions_players
    ADD CONSTRAINT sessions_players_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_players_user
    ON public.sessions_players(user_id);


ALTER TABLE IF EXISTS public.tournaments
    ADD CONSTRAINT tournaments_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tournaments_participants
    ADD CONSTRAINT tournaments_participants_tournament_id_fkey FOREIGN KEY (tournament_id)
    REFERENCES public.tournaments (tournament_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tournaments_participants
    ADD CONSTRAINT tournaments_participants_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_achievements
    ADD CONSTRAINT user_achievements_achievement_id_fkey FOREIGN KEY (achievement_id)
    REFERENCES public.achievements (achievement_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_achievements
    ADD CONSTRAINT user_achievements_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_reports
    ADD CONSTRAINT user_reports_admin_id_fkey FOREIGN KEY (admin_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.user_reports
    ADD CONSTRAINT user_reports_reported_user_id_fkey FOREIGN KEY (reported_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_reports_reported
    ON public.user_reports(reported_user_id);


ALTER TABLE IF EXISTS public.user_reports
    ADD CONSTRAINT user_reports_reporter_id_fkey FOREIGN KEY (reporter_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reports_reporter
    ON public.user_reports(reporter_id);


ALTER TABLE IF EXISTS public.user_stats
    ADD CONSTRAINT user_stats_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_stats_pkey
    ON public.user_stats(user_id);


ALTER TABLE IF EXISTS public.users_settings
    ADD CONSTRAINT users_settings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS users_settings_pkey
    ON public.users_settings(user_id);

END;